spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testSideDish;DB_CLOSE_ON_EXIT=FALSE
    username: sa

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  h2:
    console:
      enabled: true


logging:
  level:
    sql: DEBUG
